//types of messages that can be sent
public enum Message
{
    BOUNCE,
    DIRECTION_CHANGE,
    HEALTH_LOST,
    HEALTH_UPDATED,
    HIT_BY_OTHER,
    HIT_OTHER,
    INVINCIBILITY_PICKUP,
    LANDED_ON_TRAMPOLINE_PLATFORM,
    LETTER_DESTROYED,
    NO_HEALTH_REMAINING,
    NO_ARMOR_REMAINING,
    PICKUP,
    PLATFORM_COLLAPSED,
    PLATFORM_JUMPED_OFF_OF,
    PLATFORM_LANDED_ON,
    PLATFORM_RESPAWNED,
    POINTS_RECEIVED,
    PROJECTILE_EXPIRED,
    PROJECTILE_FIRED,
    STARTED_MOVEMENT,
    STATE_CHANGE,
    STOPPED_MOVEMENT,
    TURN
}